### ISSUE TITLE
Error in 

### ISSUE THREAD

**Issue by xavidp** [PPBDS/tutorial.helpers#2]
Hi, and thanks for creating this package.

I need to create some course content, and I'm reviewing your package to see whether I want to follow the route of the learnr package, or something different (since content will end up in a Moodle environment).

When clicking at "Run Document" on the first hello-world tutorial I'm tweaking, I get, errors like:

```
Listening on http://127.0.0.1:3364
Warning: Error in write_answers: could not find function "write_answers"
  3: <Anonymous>
  1: rmarkdown::run
Warning: Error in write_answers: could not find function "write_answers"
  3: <Anonymous>
  1: rmarkdown::run
(...)
```

every time I click at the buttons to download the answers (any of them: "Download RDS", "Download HTML" or "Download PDF"). the dialogue to download the file is shown, but no file is saved on disk indeed.

Hope this helps

**Comment by davidkane9** [comment]
Apologies for the delay in responding. Are you using the CRAN version?

**Comment by davidkane9** [comment]
Ahh. I think you need to include library(tutorial.helpers) in your tutorial Rmd file, just as you need to include library(learnr).

**Comment by xavidp** [comment]
Hi David, and thanks for your fedback.

It might be something else, since both packages are included in the first chunks of that Rmd file (I cloned one of the examples, trying to tweak just a few things just as some sort of hello-world approach)

I exposed my simple tweak in a Rmd file here:
https://gitlab.com/xavidp/curs-r-basic/-/blob/main/inst/tutorials/r_basic_sessio_01/tutorial.Rmd

**Comment by davidkane9** [comment]
You're right! I can replicate this error. Will fix now.

**Comment by davidkane9** [comment]
Should be fixed. Can you please:

> remove.packages("tutorial.helpers")
> remotes::install_github("PPBDS/tutorial.helpers")

And try again?

**Comment by xavidp** [comment]
Awesome, that was a fast fix! The three buttons became functional after this last commit.
In my case, where I'm using "`renv`", I installed (after removal) with the equivalent function: 

`renv::install("PPBDS/tutorial.helpers")`

(which is even shorter, btw, plus allowing better reproducibility across machines/os/environments, etc)

**Comment by davidkane9** [comment]
Nice! By the way, you are my first user. I am eager for any feedback/requests you might have! dave.kane at gmail

**Comment by xavidp** [comment]
Great, thanks David. Btw, I added a request already, to the other package :-) :

How to contribute translations to these nice tutorials you are doing 
https://github.com/PPBDS/r4ds.tutorials/issues/19

Best
