### ISSUE TITLE
i18n ?

### ISSUE THREAD

**Issue by xavidp** [PPBDS/tutorial.helpers#8]
Hi Dave:

I've seen that some strings of the r4ds.tutorials shown to users are hardcoded in functions from this package.
Are there any chances that the tutorial.helpers package can be internationalized?
I'm not expert in doing this myself, even if I have been using i18n versions of shiny apps somewhere else where I had been working in the past. 

I've made a quick search of shiny i18n alternatives, and maybe this option would be the easiest to implement and would solve the need to have localizable versions of those strings used in the tutorial.helpers package?
https://reside-ic.github.io/traduire/articles/traduire.html

General overview found here:
https://github.com/datasketch/shi18ny/#other-internationalization-packages 

Another approach:
https://posit.co/blog/translating-shiny-apps-for-international-audiences/

What do you think?

**Comment by davidkane9** [comment]
Apologies for not responding! I am open to this. What do you think is best?

**Comment by davidkane9** [comment]
No response
